appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: BOM/VtStW8TQvQO1AydZAZtdkRXwyejHrhw1VsSvpCvW36Gtpw3XrQz9tts6lC3k7BAvkJn+DcmNGDJeDqchKirSiVA2rmtf7NHHiGSgeBDfxQdCJEh+DrhAX3OhnrlDwZ7VhhAKo81VeLu+DbeKL1uSAk0wpt36roFHW8mw2Ulk4lda05BwiljWDWBiTM1hSk58t3lGf0YSp9Clp7ra6R812hkw/3tvyKl4BNofwqMqFgywjouNyDNPyyhR+Vao16FivU88kGRZL+JIIVpdzpxDJYfQIDJLVMgGaiSoIVCE1UNrscWc+Wt8AQqL98d8d6fX53zbxdyE7ywUwAVKIRbBOl9As+YmB6+8XCTSW+cmZ3lB9wGUBkNjbQfYiFZt74R7t7Z1rDNgcJqKAbKNgR+Ny/xun/G3DgqMilmy0p2sLoz4HOCV3HJLrJdwlHSs9Km3xzZPG1ibQlQHaAqKdu8inW6A/jgF+3gTCQguP0EpDQ5xUzxI8SGBc0Ubl4/XbTsZwDowOFrqyA7Xqeu3mn+Q97LuNfr72TSDTwsBZgEA95CUgRP9Jcp1TGK4UhzycvkI1IOz9T/mFD3NMkvRxJvN9fxmMFc/l2qCOYphaCKfuZyPIIHNrB8zWE2eSxjHPowqZnsGRdqxycjM3wrFxTsC3XyjvoILHlNpqVNCVyQ=}
