name: Build Conda packages with conda-build

on: push

jobs:
  build-linux:
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "Global"
            config_file: ""

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker info
      run: |
        docker info

    - name: Configure qemu
      run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset -c yes

    - name: Build using docker
      env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN  }}
          CONFIG_FILE: ${{ matrix.config_file }}
      run: |
        pwd
        FEEDSTOCK_ROOT=$(pwd)
        docker run  \
           -v "${FEEDSTOCK_ROOT}":/home/conda/feedstock_root \
           -e ANACONDA_API_TOKEN \
           -e CONFIG_FILE \
           e8035669/linux-anvil-armv7l \
           bash /home/conda/feedstock_root/.scripts/run_armv7l_build.sh

